import { readFile } from 'node:fs/promises';

import { PGlite } from '@electric-sql/pglite';

import {
  createDatabaseQuery,
  createDatabaseTransactionRunner,
  type DatabaseQuery,
  type DatabaseSQLClient,
  type DatabaseTransactionRunner,
} from '../../src/db/client.js';

export type DisposableShoppingDatabase = {
  database: DatabaseQuery;
  transactionRunner: DatabaseTransactionRunner;
  exec: (sql: string) => Promise<void>;
  close: () => Promise<void>;
};

export async function createDisposableShoppingDatabase(): Promise<DisposableShoppingDatabase> {
  const pglite = new PGlite();

  await pglite.exec(`
    CREATE TABLE shopping_locations (
      id INTEGER PRIMARY KEY,
      name TEXT,
      active BOOLEAN,
      logo TEXT,
      updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
    );

    CREATE TABLE shopping_categories (
      id INTEGER PRIMARY KEY,
      name TEXT NOT NULL
    );

    CREATE TABLE shopping_list (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL,
      brand TEXT,
      quantity INTEGER NOT NULL DEFAULT 1,
      notes TEXT,
      purchased BOOLEAN NOT NULL DEFAULT false,
      created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      category_id JSONB,
      version INTEGER NOT NULL DEFAULT 1,
      image TEXT,
      store_listings JSONB DEFAULT '[]'::jsonb
    );
  `);

  const migrationURL = new URL(
    '../../migrations/2026-07-11-001-shopping-trips.sql',
    import.meta.url,
  );
  await pglite.exec(await readFile(migrationURL, 'utf8'));

  const client: DatabaseSQLClient = {
    async query(text, values = []) {
      const result = await pglite.query(text, values);
      return { rows: result.rows as unknown[] };
    },
    release() {},
  };

  return {
    database: createDatabaseQuery(client),
    transactionRunner: createDatabaseTransactionRunner(async () => client),
    async exec(sql) {
      await pglite.exec(sql);
    },
    async close() {
      await pglite.close();
    },
  };
}
